import Blog1 from "../assets/Blog1.png"
import Blog2 from "../assets/Blog2.png"
import Blog3 from "../assets/Blog3.png"
import Blog4 from "../assets/Blog4.png"
import Blog5 from "../assets/Blog5.png"
import Blog6 from "../assets/Blog6.png"
const blogData = [
  // --- Start of Original 6 Objects ---
  {
    id: 1,
    imageUrl: Blog1,
    headline: "Healthy Living, Happier Life.",
    linkText: "Read More",
    blogContent: "Discover how small changes in daily habits can lead to a healthier and happier life. Learn practical tips for nutrition, exercise, and mental well-being.",
  },
  {
    id: 2,
    imageUrl: Blog2,
    headline: "Finding Balance in a Busy World.",
    linkText: "Read More",
    blogContent: "Explore strategies to maintain balance amidst a hectic schedule. Tips include mindfulness, prioritization, and stress management techniques.",
  },
  {
    id: 3,
    imageUrl:Blog3,
    headline: "Small Steps to Big Fitness Wins.",
    linkText: "Read More",
    blogContent: "Learn how incremental changes in your fitness routine can yield significant results over time. Simple exercises and consistency are key.",
  },
  {
    id: 4,
    imageUrl: Blog4,
    headline: "The Power of Mindful Nutrition.",
    linkText: "Read More",
    blogContent: "Mindful nutrition helps you connect with your body’s needs and make healthier choices. Understand portion control, meal planning, and mindful eating practices.",
  },
  {
    id: 5,
    imageUrl: Blog5,
    headline: "Consistent Effort: The Secret to Long-Term Fitness.",
    linkText: "Read More",
    blogContent: "Consistent effort in small exercises accumulates into meaningful fitness achievements. Focus on habits rather than drastic changes.",
  },
  {
    id: 6,
    imageUrl:Blog6,
    headline: "Transform Your Diet with Mindful Eating.",
    linkText: "Read More",
    blogContent: "Incorporate mindfulness into your meals to improve digestion, satisfaction, and long-term health. Simple awareness techniques can transform your diet.",
  },
  {
    id: 7,
    imageUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=600&q=80",
    headline: "Mastering the Art of Time Blocking.",
    linkText: "Read More",
    blogContent: "Stop multitasking and start time blocking. Learn to dedicate specific slots for high-priority tasks to boost your efficiency dramatically.",
  },
  {
    id: 8,
    imageUrl: "https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?auto=format&fit=crop&w=600&q=80",
    headline: "How to Take a Successful Digital Detox.",
    linkText: "Read More",
    blogContent: "Feeling overwhelmed by screens? Follow our guide to disconnecting for a weekend to reset your mind and regain focus.",
  },
  {
    id: 9,
    imageUrl: "https://placehold.co/600x400/f59e0b/ffffff?text=Financial+Freedom",
    headline: "Your First Steps Towards Financial Freedom.",
    linkText: "Read More",
    blogContent: "Essential advice on budgeting, clearing debt, and starting your investment journey, even with a small income.",
  },
  {
    id: 10,
    imageUrl: "https://placehold.co/600x400/ef4444/ffffff?text=Sleep+Science",
    headline: "The Science of Sleep: Optimizing Your Rest.",
    linkText: "Read More",
    blogContent: "Dive into the mechanics of sleep cycles and discover habits that will ensure you wake up feeling truly refreshed every morning.",
  },
  {
    id: 11,
    imageUrl: "https://placehold.co/600x400/6366f1/ffffff?text=Creative+Ideas",
    headline: "Unleashing Your Inner Creativity.",
    linkText: "Read More",
    blogContent: "Simple prompts and exercises designed to break through creative blocks and start generating innovative ideas today.",
  },
  {
    id: 12,
    imageUrl: "https://placehold.co/600x400/06b6d4/ffffff?text=Mental+Health",
    headline: "Building Resilience: Bouncing Back from Setbacks.",
    linkText: "Read More",
    blogContent: "Learn powerful psychological strategies to cope with disappointment and strengthen your mental resilience for long-term well-being.",
  },
  {
    id: 13,
    imageUrl: "https://placehold.co/600x400/f87171/ffffff?text=Travel+Tips",
    headline: "Travel Hacking: Seeing the World on a Budget.",
    linkText: "Read More",
    blogContent: "Insider tips on finding cheap flights, affordable accommodation, and maximizing travel rewards to explore more for less.",
  },
  {
    id: 14,
    imageUrl: "https://placehold.co/600x400/22c55e/ffffff?text=Home+Office",
    headline: "Designing the Perfect Home Workspace.",
    linkText: "Read More",
    blogContent: "How to set up an ergonomic and productivity-boosting home office, regardless of the size of your space.",
  },
  {
    id: 15,
    imageUrl: "https://placehold.co/600x400/eab308/ffffff?text=Meditation",
    headline: "Meditation Made Simple: A 5-Minute Guide.",
    linkText: "Read More",
    blogContent: "Don't have time to meditate? We show you how to find calm and focus in just five minutes a day.",
  },
  {
    id: 16,
    imageUrl: "https://placehold.co/600x400/d946ef/ffffff?text=Career+Growth",
    headline: "Networking: Building Your Professional Tribe.",
    linkText: "Read More",
    blogContent: "Effective techniques for professional networking that go beyond exchanging business cards and build genuine connections.",
  },
  {
    id: 17,
    imageUrl: "https://placehold.co/600x400/dc2626/ffffff?text=Self+Improvement",
    headline: "The Habit Loop: Making Good Habits Stick.",
    linkText: "Read More",
    blogContent: "Understand the science behind habit formation (Cue, Routine, Reward) and how to apply it to build lasting positive changes.",
  },
  {
    id: 18,
    imageUrl: "https://placehold.co/600x400/0f766e/ffffff?text=Cooking+Basics",
    headline: "Essential Cooking Skills for Complete Beginners.",
    linkText: "Read More",
    blogContent: "Master the fundamental techniques—chopping, searing, and seasoning—to start cooking delicious, healthy meals tonight.",
  },
  {
    id: 19,
    imageUrl: "https://placehold.co/600x400/4f46e5/ffffff?text=Communication",
    headline: "Improving Listening: The Key to Better Relationships.",
    linkText: "Read More",
    blogContent: "Active listening is a superpower. Learn how to truly hear and understand others to deepen your personal and professional connections.",
  },
  {
    id: 20,
    imageUrl: "https://placehold.co/600x400/0891b2/ffffff?text=Goal+Setting",
    headline: "SMART Goals: A Framework for Success.",
    linkText: "Read More",
    blogContent: "Learn how to define Specific, Measurable, Achievable, Relevant, and Time-bound goals that you can actually stick to.",
  },
  {
    id: 21,
    imageUrl: "https://placehold.co/600x400/fb7185/ffffff?text=Mindfulness",
    headline: "Mindfulness in Motion: Daily Living with Awareness.",
    linkText: "Read More",
    blogContent: "Integrate mindfulness into everyday activities like walking, eating, and doing chores to stay present and reduce anxiety.",
  },
  {
    id: 22,
    imageUrl: "https://placehold.co/600x400/10b981/ffffff?text=Morning+Routine",
    headline: "The 5 AM Club: Is an Early Wake-up Right for You?",
    linkText: "Read More",
    blogContent: "We explore the pros and cons of an early morning routine and offer alternatives if waking up at dawn isn't your style.",
  },
  {
    id: 23,
    imageUrl: "https://placehold.co/600x400/f59e0b/ffffff?text=Side+Hustle",
    headline: "Top 5 Side Hustles You Can Start This Month.",
    linkText: "Read More",
    blogContent: "Actionable ideas for generating extra income using skills you already possess, from freelance writing to virtual assistance.",
  },
  {
    id: 24,
    imageUrl: "https://placehold.co/600x400/7c3aed/ffffff?text=Minimalism",
    headline: "The Power of Less: Embracing Minimalism.",
    linkText: "Read More",
    blogContent: "Declutter your home and your mind. Discover how a minimalist lifestyle can lead to less stress and greater contentment.",
  },
  {
    id: 25,
    imageUrl: "https://placehold.co/600x400/06b6d4/ffffff?text=Reading+Tips",
    headline: "How to Read More Books in a Year.",
    linkText: "Read More",
    blogContent: "Practical strategies like speed reading and active reading that help you consume and retain information from books faster.",
  },
  {
    id: 26,
    imageUrl: "https://placehold.co/600x400/ec4899/ffffff?text=Productive+Weekend",
    headline: "Making Your Weekends Productive and Restful.",
    linkText: "Read More",
    blogContent: "Learn to balance rest and productivity so you start your Monday feeling energized instead of exhausted.",
  },
  {
    id: 27,
    imageUrl: "https://placehold.co/600x400/475569/ffffff?text=Stoicism",
    headline: "Ancient Wisdom for Modern Life: An Intro to Stoicism.",
    linkText: "Read More",
    blogContent: "Explore the core tenets of Stoic philosophy and how they can help you manage emotions and find peace in chaos.",
  },
  {
    id: 28,
    imageUrl: "https://placehold.co/600x400/a3e635/ffffff?text=Fitness+Motivation",
    headline: "Finding Motivation When You Feel Like Quitting.",
    linkText: "Read More",
    blogContent: "Tactics for reigniting your fitness motivation, overcoming plateaus, and maintaining consistency when your willpower dips.",
  },
  {
    id: 29,
    imageUrl: "https://placehold.co/600x400/94a3b8/ffffff?text=Tech+Trends",
    headline: "Understanding the Basics of AI and Machine Learning.",
    linkText: "Read More",
    blogContent: "A non-technical explanation of artificial intelligence and its real-world applications that are changing everyday life.",
  },
  {
    id: 30,
    imageUrl: "https://placehold.co/600x400/fca5a5/ffffff?text=Personal+Growth",
    headline: "Journaling for Self-Discovery and Mental Clarity.",
    linkText: "Read More",
    blogContent: "The benefits of daily journaling and simple methods for getting started, even if you feel you have nothing to write about.",
  },
  {
    id: 31,
    imageUrl: "https://placehold.co/600x400/38bdf8/ffffff?text=Healthy+Aging",
    headline: "Longevity Secrets: Habits for a Longer, Healthier Life.",
    linkText: "Read More",
    blogContent: "Research-backed tips on diet, movement, and social connection that contribute to healthy aging and vitality.",
  },
  {
    id: 32,
    imageUrl: "https://placehold.co/600x400/e879f9/ffffff?text=Career+Shift",
    headline: "Making the Leap: A Guide to Career Changing.",
    linkText: "Read More",
    blogContent: "Practical steps for researching new fields, upskilling, and transitioning successfully into a new career path.",
  },
  {
    id: 33,
    imageUrl: "https://placehold.co/600x400/fb923c/ffffff?text=Digital+Nomad",
    headline: "The Digital Nomad Lifestyle: Pros and Cons.",
    linkText: "Read More",
    blogContent: "An honest look at working remotely while traveling, covering everything from visas to maintaining work-life balance.",
  },
  {
    id: 34,
    imageUrl: "https://placehold.co/600x400/4ade80/ffffff?text=Photography",
    headline: "Smartphone Photography: Taking Stunning Shots.",
    linkText: "Read More",
    blogContent: "How to use your phone's camera settings and composition rules to capture professional-looking photos every time.",
  },
  {
    id: 35,
    imageUrl: "https://placehold.co/600x400/9333ea/ffffff?text=Interpersonal",
    headline: "Setting Healthy Boundaries in Relationships.",
    linkText: "Read More",
    blogContent: "Learn why boundaries are crucial for mental health and how to communicate your needs clearly and respectfully.",
  },
  {
    id: 36,
    imageUrl: "https://placehold.co/600x400/78716c/ffffff?text=Stress+Relief",
    headline: "Breathing Exercises to Combat Anxiety Instantly.",
    linkText: "Read More",
    blogContent: "Three simple breathing techniques you can use anywhere, anytime to quickly calm your nervous system and reduce panic.",
  },
  {
    id: 37,
    imageUrl: "https://placehold.co/600x400/facc15/ffffff?text=Investment",
    headline: "Understanding Index Funds: Investing Made Easy.",
    linkText: "Read More",
    blogContent: "A beginner-friendly guide to low-cost index fund investing, a powerful strategy for long-term wealth building.",
  },
  {
    id: 38,
    imageUrl: "https://placehold.co/600x400/2dd4bf/ffffff?text=Productivity+Tools",
    headline: "The Best Productivity Apps of the Year.",
    linkText: "Read More",
    blogContent: "Review of the top digital tools for note-taking, project management, and focus to streamline your work.",
  },
  {
    id: 39,
    imageUrl: "https://placehold.co/600x400/f87171/ffffff?text=Emotional+Intelligence",
    headline: "Boosting Your Emotional Intelligence (EQ).",
    linkText: "Read More",
    blogContent: "Why EQ matters more than IQ, and practical exercises to improve your self-awareness and empathy towards others.",
  },
  {
    id: 40,
    imageUrl: "https://placehold.co/600x400/818cf8/ffffff?text=Public+Speaking",
    headline: "Overcoming the Fear of Public Speaking.",
    linkText: "Read More",
    blogContent: "Proven methods to manage stage fright, structure a powerful presentation, and captivate any audience.",
  },
  {
    id: 41,
    imageUrl: "https://placehold.co/600x400/06b6d4/ffffff?text=Decluttering",
    headline: "The KonMari Method: Does it Really Work?",
    linkText: "Read More",
    blogContent: "An in-depth look at the famous tidying method and how it can bring joy and order to your living space.",
  },
  {
    id: 42,
    imageUrl: "https://placehold.co/600x400/10b981/ffffff?text=Hydration",
    headline: "The Surprising Benefits of Optimal Hydration.",
    linkText: "Read More",
    blogContent: "It's more than just water! Discover how proper hydration impacts your energy, skin, and cognitive function.",
  },
  {
    id: 43,
    imageUrl: "https://placehold.co/600x400/f97316/ffffff?text=Reading+Habits",
    headline: "How to Build a Powerful Reading Habit.",
    linkText: "Read More",
    blogContent: "Transform reading from a chore into a joy with strategic tips on book selection and setting realistic daily goals.",
  },
  {
    id: 44,
    imageUrl: "https://placehold.co/600x400/ef4444/ffffff?text=Parenting",
    headline: "Positive Parenting: Nurturing Your Child's Growth.",
    linkText: "Read More",
    blogContent: "Techniques focused on empathy, clear communication, and non-punitive discipline to foster a positive home environment.",
  },
  {
    id: 45,
    imageUrl: "https://placehold.co/600x400/6366f1/ffffff?text=Learning+Skills",
    headline: "The Feynman Technique: Learn Anything Faster.",
    linkText: "Read More",
    blogContent: "Use this four-step method, named after a Nobel laureate, to understand complex topics and test your knowledge effectively.",
  },
  {
    id: 46,
    imageUrl: "https://placehold.co/600x400/8b5cf6/ffffff?text=Personal+Style",
    headline: "Developing a Personal Style That Boosts Confidence.",
    linkText: "Read More",
    blogContent: "Moving beyond trends to define a wardrobe that reflects your true personality and makes you feel great every day.",
  },
  {
    id: 47,
    imageUrl: "https://placehold.co/600x400/14b8a6/ffffff?text=Writing+Tips",
    headline: "Write Better Emails: Professional Communication.",
    linkText: "Read More",
    blogContent: "Tips for structuring clear, concise, and professional emails that get straight to the point and ensure a quick response.",
  },
  {
    id: 48,
    imageUrl: "https://placehold.co/600x400/f59e0b/ffffff?text=Music+Therapy",
    headline: "The Healing Power of Music: Sound Therapy.",
    linkText: "Read More",
    blogContent: "Explore how different musical genres and frequencies can be used as a tool for relaxation, focus, and emotional release.",
  },
  {
    id: 49,
    imageUrl: "https://placehold.co/600x400/3b82f6/ffffff?text=Volunteering",
    headline: "Finding Fulfillment: The Benefits of Volunteering.",
    linkText: "Read More",
    blogContent: "Discover how giving back to your community can boost your mental health, expand your network, and bring deep personal satisfaction.",
  },
  {
    id: 50,
    imageUrl: "https://placehold.co/600x400/f56565/ffffff?text=Outdoor+Fitness",
    headline: "The Joy of Outdoor Workouts: Beyond the Gym.",
    linkText: "Read More",
    blogContent: "Incorporate nature into your fitness routine. We cover hiking, outdoor yoga, and running for a refreshing exercise experience.",
  },
];

export default blogData;